all: TMA1Question1 TMA1Question2 TMA1Question3 TMA1Question4 TMA1Question5

TMA1Question1:TMA1Question1.cpp
	g++ -o TMA1Question1 TMA1Question1.cpp 
TMA1Question2:TMA1Question2.cpp
	g++ -o TMA1Question2 TMA1Question2.cpp 
TMA1Question3:TMA1Question3.cpp
	g++ -o TMA1Question3 TMA1Question3.cpp 
TMA1Question4:TMA1Question4.cpp
	g++ -o TMA1Question4 TMA1Question4.cpp
TMA1Question5:TMA1Question5.cpp
	g++ -o TMA1Question5 TMA1Question5.cpp
clear:
	rm TMA1Question1 TMA1Question2 TMA1Question3 TMA1Question4 TMA1Question5
debug:
	$(CPP) TMA1Question1.cpp
