all: TMA4Question1 TMA4Question2 TMA4Question3 test

TMA3Question1:TMA4Question1.cpp
	g++ -o TMA3Question1 TMA3Question1.cpp 
TMA3Question2:TMA4Question2.cpp
	g++ -o TMA4Question2 TMA3Question2.cpp 
TMA3Question3:TMA4Question3.cpp
	g++ -o TMA3Question3 TMA3Question3.cpp 
Test:test.cpp
	g++ -o test test.cpp
clear:
	rm TMA4Question1 TMA4Question2 TMA4Question3 test
