all: TMA1Question1 TMA1Question2 TMA1Question3 TMA1Question4 TMA1Question5 TMA2Question1 TMA2Question2 TMA2Question3 TMA2Question4 TMA3Question1 TMA3Question2 TMA3Question3 TMA4Question1 TMA4Question2 TMA4Question3

TMA1Question1:TMA1Question1.cpp
	g++ -o TMA1Question1 TMA1Question1.cpp 
TMA1Question2:TMA1Question2.cpp
	g++ -o TMA1Question2 TMA1Question2.cpp 
TMA1Question3:TMA1Question3.cpp
	g++ -o TMA1Question3 TMA1Question3.cpp 
TMA1Question4:TMA1Question4.cpp
	g++ -o TMA1Question4 TMA1Question4.cpp
TMA1Question5:TMA1Question5.cpp
	g++ -o TMA1Question5 TMA1Question5.cpp
TMA2Question1:TMA2Question1.cpp
	g++ -o TMA2Question1 TMA2Question1.cpp 
TMA2Question2:TMA2Question2.cpp
	g++ -o TMA2Question2 TMA2Question2.cpp 
TMA2Question3:TMA2Question3.cpp
	g++ -o TMA2Question3 TMA2Question3.cpp 
TMA2Question4:TMA2Question4.cpp
	g++ -o TMA2Question4 TMA2Question4.cpp
TMA2Question5:TMA2Question5.cpp
	g++ -o TMA2Question5 TMA2Question5.cpp
TMA3Question1:TMA3Question1.cpp
	g++ -o TMA3Question1 TMA3Question1.cpp
TMA3Question2:TMA3Question2.cpp
	g++ -o TMA3Question2 TMA3Question2.cpp 
TMA3Question3:TMA3Question3.cpp
	g++ -o TMA3Question3 TMA3Question3.cpp 
TMA4Question1:TMA4Question1.cpp
	g++ -o TMA4Question1 TMA4Question1.cpp 
TMA4Question2:TMA4Question2.cpp
	g++ -o TMA4Question2 TMA4Question2.cpp 
TMA4Question3:TMA4Question3.cpp
	g++ -o TMA4Question3 TMA4Question3.cpp 
clear:
	rm TMA1Question1 TMA1Question2 TMA1Question3 TMA1Question4 TMA1Question5 TMA2Question1 TMA2Question2 TMA2Question3 TMA2Question4 TMA3Question1 TMA3Question2 TMA3Question3 TMA4Question1 TMA4Question2 TMA4Question3

debug:
	$(CPP) TMA1Question1.cpp
