all: TMA3Question1 TMA3Question2 TMA3Question3 test

TMA3Question1:TMA3Question1.cpp
	g++ -o TMA3Question1 TMA3Question1.cpp
TMA3Question2:TMA3Question2.cpp
	g++ -o TMA3Question2 TMA3Question2.cpp 
TMA3Question3:TMA3Question3.cpp
	g++ -o TMA3Question3 TMA3Question3.cpp 
Test:test.cpp
	g++ -o test test.cpp
clear:
	rm TMA3Question1 TMA3Question2 TMA3Question3 test
