all: TMA2Question1 TMA2Question2 TMA2Question3 TMA2Question4 

TMA2Question1:TMA2Question1.cpp
	g++ -o TMA2Question1 TMA2Question1.cpp 
TMA2Question2:TMA2Question2.cpp
	g++ -o TMA2Question2 TMA2Question2.cpp 
TMA2Question3:TMA2Question3.cpp
	g++ -o TMA2Question3 TMA2Question3.cpp 
TMA2Question4:TMA2Question4.cpp
	g++ -o TMA2Question4 TMA2Question4.cpp
TMA2Question5:TMA2Question5.cpp
	g++ -o TMA2Question5 TMA2Question5.cpp
clear:
	rm TMA2Question1 TMA2Question2 TMA2Question3 TMA2Question4  
